### ISSUE TITLE
urg_node no executable found

### ISSUE THREAD

**Issue by yechun1** [bponsler/urg_node#2]
I try to launch turtlebot2 cartographer with laser urg_node, but could not found urg_node by get_executable_path.  Also,  run "ros2 run urg_node urg_node" , it says "no executable found."

As check, the urg_node binaries have been generated under install_isolated/urg_node/bin/ , instead of install_isolated/urg_node/lib/urg_node/ (compare with ROS1), could we fix it for uniform interface.

Details:
launch `ros2 pkg prefix turtlebot2_cartographer`/share/turtlebot2_cartographer/launch/turtlebot_carto_2d.py
code
//
 ld.add_process(
        cmd=[get_executable_path(package_name=package, executable_name='urg_node')],
        name='urg_node',
        exit_handler=restart_exit_handler,
    )
//

root@robot1:~/ros2_dev# ros2 run urg_node urg_node
No executable found

**Comment by bponsler** [comment]
Closing the issue as it should now be installed in lib/urg_node
